### ISSUE TITLE
Best practice for caching?

### ISSUE THREAD

**Issue by lox** [cashapp/activate-hermit#1]
Loving being able to use Hermit and GitHub Actions!

What is the best way to cache hermit packages? I was considering something like this:

```yaml
steps:
  - uses: actions/checkout@v3
  - name: Cache hermit
    id: cache-hermit
    uses: actions/cache@v3
    with:
      path: .cache/hermit
      key: ${{ runner.os }}-hermit-${{ hashFiles('bin/*.pkg') }}
  - uses: cashapp/activate-hermit@v1
```

Is this something that could be included in the action in the same way that the setup-node action has optional caching?
